core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('category/<slug:slug>/', views.category_page, name='category_page'),
    path('post/<slug:slug>/', views.post_page, name='post_page'),
    path('tag/<slug:slug>/', views.tag_page, name='tag_page'),
    path('search/', views.SearchView.as_view(), name='search_results'),
    path('about', views.about, name='about'),
    path('contacts', views.contacts, name='contacts'),
    path('privacy', views.privacy, name='privacy'),
    path('drafts/', views.drafts, name='drafts'),
]

techcoreua/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from filebrowser.sites import site

from core import views

from . import settings

from .sitemaps import PostSitemap, CategorySitemap, TagsSitemap, StaticSitemap

from .feeds import LatestPostsFeed

sitemaps = {'static': StaticSitemap, 'category': CategorySitemap, 'tag': TagsSitemap, 'post': PostSitemap,}

urlpatterns = [
    path('admin/filebrowser/', site.urls),
   path('grappelli/', include('grappelli.urls')),
    path('admin_panel/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls', namespace='core')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('feed/rss', LatestPostsFeed(), name='post_feed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


handler404 = 'core.views.custom_page_not_found_view'
handler500 = 'core.views.custom_error_view'
handler403 = 'core.views.custom_permission_denied_view'
handler400 = 'core.views.custom_bad_request_view'

templates/about-page.html
{% extends 'base.html' %}
{% load static %}

{% block meta_tags %}      
    <title>Про нас | Techcoreua</title>
    <meta name = "description" content = "Детальна інформація про проект Techcoreua">


    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@techcoreua" />
    <!-- <meta name="twitter:creator" content="@nickbilton" /> -->
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:title" content="Про нас | Techcoreua" />
    <meta property="og:description" content="Детальна інформація про проект Techcoreua" />
    <meta property="og:image" content="https://{{request.get_host}}/static/logo_big.png" />
{% endblock meta_tags %}

{% block content %}
    <div class="container mt-5 mb-2">
        <section class="about_post pt-5">
            <h1>Techcoreua - що це?</h1><hr>
            <p>
                Це проект, створений для розвитку українського інтернет-ком'юніті. <br>
                Наша мета - надавати якісний техно-контент <strong>українською(!)</strong> мовою та створити потужне україномовне середовище технофанів. <br>
                Techcoreua - портал, який висвітлює різні технологічні середовища: від Open Source світу, до закритої екосистеми Microsoft.
                В нас ви знайдете корисні мануали, свіжі і цікаві новини, огляди програм та дистрибутивів, авторські статті.
                Також ви вільно можете обговорити з іншими відвідувачами той чи інший допис в коментарях.
            </p>
            <p>
                Рекомендуємо також підписатися на наші соцмережі, там ви бачитимете анонси, нові дописи та контент, який не потрапляє на сайт.
            </p>
            
            
        </section>

        



        <div class="social-panel pt-5 pb-5">
            <a href="https://twitter.com/techcoreua" class="nav-link nav-link-footer social-link twitt" target="_blank"><i class="fab fa-twitter"></i> Twitter</a>
            <a href="https://www.instagram.com/techcoreua/" class="nav-link social-link instag" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
            <a href="https://t.me/techcoreua" class="nav-link social-link teleg" target="_blank"><i class="fab fa-telegram"></i> Telegram</a>
            <a href="https://www.facebook.com/techcoreua" class="nav-link social-link faceb" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>    
        </div>   

        <div class="logoimg mb-5 pt-5 mt-2" style="text-align: center;">
            <img src="{% static '/logo_big.png' %}" alt="logo" style="width: 50%;" class="img-fluid">
        </div>

    </div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- META PREVIEW SETTINGS -->
        {% block meta_tags %}
          
        {% endblock meta_tags %}

        <!-- sharethis js -->
        <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5f8f035408847600125c2fdb&product=inline-share-buttons" async="async"></script>

        
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-178463432-2"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-178463432-2');
        </script>

        <!-- adsense google -->
        <script data-ad-client="ca-pub-4616331702897121" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

        <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" id="theme-style">
        <link href="https://techcoreua.tk/" rel="canonical">
    </head>
<body>
  <header>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark custom-navbar fixed-top">
      <a class="custom-brand" href="/"><h2>techcoreua </h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          {% for category in request.categories %}
          <li class="nav-item nav-item-custom">
          <a class="nav-link nav-link-custom" href="{{category.get_absolute_url}}" title="{{category.description}}">{{category.title}}</a>
          </li>
          {% endfor %}
          
          
        </ul>

        <div class="switchbox" style="display: flex;">

          <div class="sun theme-mode custom-hovers" data-mode='light'>
            <i class="fas fa-lightbulb fa-lg"></i>
          </div>
  
          <div class="moon theme-mode custom-hovers" data-mode='dark'>
            <i class="far fa-lightbulb fa-lg"></i>
          </div>
  
        </div>

      

        <form class="form-inline mb-4 my-lg-0" method="GET" action="{% url 'core:search_results' %}">
          <input required oninvalid="this.setCustomValidity('Будь ласка, вкажіть дані для пошуку')" onchange="this.setCustomValidity('')" class="form-control mr-sm-2 custom-input" type="text" placeholder="Введіть запит" name="q" id="search-input">
          <button class="btn my-2 my-sm-0 custom-search-button" type="submit">Пошук</button>
        </form>

        {% if request.user.is_authenticated %}
          <div class="btn-group">
            {% if request.user.is_staff %}
                <a href="{% url 'admin:index' %}" class="nav-link"><strong>Адмінпанель</strong></a>
                <a href="/admin/filebrowser/browse/" class="nav-link"><strong>Файли</strong></a>
                <a href="/drafts/" class="nav-link"><strong>Чернетки</strong></a>
            {% endif %}
            <a class="nav-link" href="{% url 'account_logout' %}"><strong><i class="fas fa-sign-out-alt"></i></strong></a>
          </div>
        {% endif %}


      </div>
    </nav>
  </header>

  <main class="main">
    
    


        {% block content %}
            
        {% endblock content %}




  </main>

  <footer class="footer mt-auto">
    <div class="sitemap text-center pt-4 pb-4">
      Контакти та інформація <br>
      <!-- {% for category in categories %}
        <a class="nav-link nav-link-footer p-1" href="{{category.get_absolute_url}}">{{category.title}}</a>
      {% endfor %} -->
      <a class="nav-link nav-link-footer p-1" href="{% url 'core:contacts' %}">Контакти</a>
      <a class="nav-link nav-link-footer p-1" href="{% url 'core:about' %}">Про нас</a>
    </div>

    <div class="container text-center pt-4 pb-4">
      Techcoreua © Всі права захищено <br>
      <a href="{% url 'core:privacy' %}" class="nav-link nav-link-footer">Політика приватності</a>
    </div>

    <div class="social text-center pt-4 pb-4">
      Techcoreua в соцмережах <br>
      <!-- <a href="https://twitter.com/techcoreua" class="nav-link nav-link-footer" target="_blank"><i class="fab fa-twitter"></i> Twitter | @techcoreua</a> -->
      <!-- <a href="https://www.instagram.com/techcoreua/" class="nav-link nav-link-footer" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
      <a href="https://t.me/techcoreua" class="nav-link nav-link-footer" target="_blank"><i class="fab fa-telegram"></i> Telegram</a>
      <a href="https://www.facebook.com/techcoreua" class="nav-link nav-link-footer" target="_blank"><i class="fab fa-facebook"></i> Facebook</a> -->
        <div class="social-panel pt-3 pb-3">
          <a href="https://twitter.com/techcoreua" class="nav-link nav-link-footer social-link twitt" target="_blank"><i class="fab fa-twitter"></i> Twitter</a>
          <a href="https://www.instagram.com/techcoreua/" class="nav-link nav-link-footer social-link instag" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
          <a href="https://t.me/techcoreua" class="nav-link nav-link-footer social-link teleg" target="_blank"><i class="fab fa-telegram"></i> Telegram</a>
          <a href="https://www.facebook.com/techcoreua" class="nav-link nav-link-footer social-link faceb" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>    
      </div>
    </div>
  </footer>


  <script>
    var def_style_src = '{% static "css/style.css" %}'
    var dark_style_src = '{% static "css/dark.css" %}'
  </script>

  <script>
    // change yourdomain.in to your domain
    var disqus_config = function () {
      this.page.url = "{{request.build_absolute_uri}}"; 
      this.page.identifier = "{{request.build_absolute_uri}}"; 
    };
    
    // Modify End
    
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://techcoreua.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>

  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                              
  <script>
  
  
  
  </script>

  <script>
    // document.getElementById('search-input').setCustomValidity('Будь ласка, вкажіть дані для пошуку');
  </script>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ecc04f3b39.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <!-- <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script> -->

</body>
</html>

templates/category-page.html
{% extends 'base.html' %}
{% load static %}

{% block meta_tags %}      
    <title>{{category.title}} | Techcoreua</title>
    <meta name = "description" content = "{{category.description}}">


    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@techcoreua" />
    <!-- <meta name="twitter:creator" content="@tse_ne_ia" /> -->
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:title" content="{{category.title}} | Techcoreua" />
    <meta property="og:description" content="{{category.description}}" />
    <meta property="og:image" content="https://{{request.get_host}}/static/logo_big.png" />
{% endblock meta_tags %}

{% block content %}
        <div class="col-12 mt-5 pt-5 category-page-container">
            <div class="wrapper">
                {% if category.title == 'Microsoft' %}
                <h3 class="category-pageh3 text-center"><i class="fab fa-microsoft"></i> {{category.title}}</h3><hr>
                {% elif category.title == 'Linux' %}
                <h3 class="category-pageh3 text-center"><i class="fab fa-linux"></i> {{category.title}}</h3><hr>
                {% elif category.title == 'Мануали' %}
                <h3 class="category-pageh3 text-center"><i class="fas fa-tools"></i> {{category.title}}</h3><hr>
                {% elif category.title == 'Огляди' %}
                <h3 class="category-pageh3 text-center"><i class="far fa-eye"></i> {{category.title}}</h3><hr>
                {% else %}
                <h3 class="category-pageh3 text-center">{{category.title}}</h3><hr>
                {% endif %}
                
                <div class="category-page-posts">

                    {% for post in posts %}
                        <div class="category-page-post">
                            <img class="img-fluid category-page-post-img" src="{{post.main_image.url}}" alt="" srcset="">
                            <div class="category-page-post-text">
                                <a class="read_more" href="{{post.get_absolute_url}}"><h4 class="post-titleh4">{{post.title}}</h4></a>
                                <p class="autor-date-area"><i class="far fa-user"></i> {{post.author.first_name}} {{post.author.last_name}} / <i class="far fa-clock"></i> {{post.creating_date}}</p>
                                <p class="post-preview">{{post.preview_text}}</p>
    
                            </div>
                        </div>
                    {% endfor %}
                    
                </div>
                <div class="page-navigation mt-5 mb-5">
                    <div class="button">
                        {% if posts.has_other_pages %}
                        <ul class="pagination">
                            {% if posts.has_previous %}
                            <li><a class="btn load-more" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                            <li class="disabled btn load-more"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in posts.paginator.page_range %}
                                {% if posts.number == i %}
                                    <li class="btn lead-more-disabled"><span>{{ i }} </span></li>
                                {% else %}
                                    <li><a class="btn load-more" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                            <li><a class="btn load-more" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                            {% else %}
                            <li class="disabled btn load-more"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
    
            </div>
            <div class="sidebar-sticky">
                <div class="sidebar mb-5">

                    <h4 class="category-pageh3 text-center">Підписуйтеся на нас в соцмережах</h4>
                    <div class="social-panel pt-3 pb-3">
                        <a href="https://www.instagram.com/techcoreua/" class="nav-link social-link instag" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
                        <a href="https://t.me/techcoreua" class="nav-link social-link teleg" target="_blank"><i class="fab fa-telegram"></i> Telegram</a>
                        <a href="https://www.facebook.com/techcoreua" class="nav-link social-link faceb" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>    
                    </div>              
                    
                    {% if category.title != 'Мануали' %}
                        <h3 class="category-pageh3 text-center">Останні мануали</h3><hr>
                        <div class="sidebar-posts">
            
                            {% for manual in manuals_posts %}
                            <div class="sidebar-page-post">
                                <img class="img-fluid sidebar-page-post-img" src="{{manual.main_image.url}}" alt="" srcset="">
                                <div class="sidebar-page-post-text">
                                    <a class="read_more" href="{{manual.get_absolute_url}}"><h4 class="post-titleh4">{{manual.title}}</h4></a>
                                    <p class="autor-date-area">{{manual.author.first_name}} {{manual.author.last_name}} / {{manual.creating_date}}</p>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </div>
                    {% endif %}
                    
                    {% if category.title != 'Огляди' %}
                    <h3 class="category-pageh3 text-center mt-3">Останні огляди</h3><hr>
                    <div class="sidebar-posts">
                        
                        {% for review in review_posts %}
                        <div class="sidebar-page-post">
                            <img class="img-fluid sidebar-page-post-img" src="{{review.main_image.url}}" alt="" srcset="">
                            <div class="sidebar-page-post-text">
                                <a class="read_more" href="{{review.get_absolute_url}}"><h4 class="post-titleh4">{{review.title}}</h4></a>
                                <p class="autor-date-area">{{review.author.first_name}} {{review.author.last_name}} / {{review.creating_date}}</p>
                            </div>
                        </div>
                        {% endfor %}
        
                    </div>
                    {% endif %}


                    <h3 class="category-pageh3 text-center">Хмара тегів</h3><hr>
                    <div class="tags_cloud mb-3">
                        {% for tag in tags %}
                            <a href="{{tag.get_absolute_url}}" class="btn">{{tag.title}}</a>
                        {% endfor %}
        
                    </div>


                </div>
        
            </div>
        </div>
    {% endblock content %}

templates/contacts-page.html
{% extends 'base.html' %}

{% block meta_tags %}      
    <title>Контакти | Techcoreua</title>
    <meta name = "description" content = "Як можна зв'язатися з нами">


    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@techcoreua" />
    <!-- <meta name="twitter:creator" content="@nickbilton" /> -->
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:title" content="Контакти | Techcoreua" />
    <meta property="og:description" content="Як можна зв'язатися з нами" />
    <meta property="og:image" content="https://{{request.get_host}}/static/logo_big.png" />
{% endblock meta_tags %}

{% block content %}
    <div class="container mt-5 mb-5">

        <section class="contacts_section pt-2">
            <h1 class="mt-5">Контактна інформація</h1><hr>
            <p> 
                Ви можете звернутися до команди Techcoreua, надіславши лист на нашу електронну адресу або заповнивши форму нижче.<br>
                В темі листа вкажіть причину, з якої ви до нас звертаєтеся. <br>
                Якщо ви хочете повідомити про несправність сайту, знайшли застарілу інформацію чи помилку в тексті - вкажіть в темі "Потребує виправлення". 
            </p>

            <p>Наша електронна адреса - <a href="mailto:techcoreua@gmail.com">techcoreua@gmail.com</a></p>

            <p>Також слідкуйте за нашими соцмережами, щоб завжи бути в курсі всіх новин та анонсів</p>
        </section>

        <div class="social-panel pt-5 pb-5">
            <a href="https://twitter.com/techcoreua" class="nav-link nav-link-footer social-link twitt" target="_blank"><i class="fab fa-twitter"></i> Twitter</a>
            <a href="https://www.instagram.com/techcoreua/" class="nav-link social-link instag" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
            <a href="https://t.me/techcoreua" class="nav-link social-link teleg" target="_blank"><i class="fab fa-telegram"></i> Telegram</a>
            <a href="https://www.facebook.com/techcoreua" class="nav-link social-link faceb" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>    
        </div>   


        <section id="mail_me" class="mt-5">
            <div class="">
                <h3 style="text-align:center">Маєте що розповісти чи запитати?</h3>
    
                <form id="contact-form" action="https://formspree.io/f/xyybevzg" method="POST" class="mt-5">
                    <label for="">Ім'я</label>
                    <input type="text" name="name" class="input-field">
    
                    <label for="">Тема</label>
                    <input type="text" name="subject" class="input-field">
    
                    <label for="">Електронна адреса</label>
                    <input type="text" name="email" class="input-field">
    
                    <label for="">Повідомлення</label>
                    <textarea style="resize: none" name="message" class="input-field"></textarea>
    
    
                    <input id='submit-btn' class="btn" type="submit" value='Надіслати'>
                </form>
    
            </div>
        </section>
    </div>
{% endblock content %}

templates/drafts-page.html
{% extends 'base.html' %}

{% block meta_tags %}      
    <title>Чернетки | Techcoreua</title>
    
{% endblock meta_tags %}

{% block content %}
    <div class="mt-5 mb-5 pt-5">
        {% for draft in drafts %}
        <div class="container">
            <div class="post-container">
                <img src="{{draft.main_image.url}}" alt="" class="img-fluid">
                <p class="autor-date-area"><i class="far fa-user"></i> {{draft.author.first_name}} {{draft.author.last_name}} / <i class="far fa-clock"></i> {{draft.creating_date}}</p>
                <hr>
                <div class="post-text">
                    <h3 class="post-titleh3 p-p-dark">{{draft.title}}</h3>
                    <p class="post-preview">{{draft.preview_text|safe}}</p>
                    <p class="p-p-post-text">{{draft.text|safe}}</p>
                    <div class="tags_cloud mt-4 bg-transparent">
                        {% for tag in draft.tags.all %}
                            <a href="{{tag.get_absolute_url}}" class="btn">{{tag.title}}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sharethis-inline-share-buttons mb-5"></div>
                
                
            </div>
        </div><hr>  
        {% endfor %}
    </div>
{% endblock content %}

templates/post-page.html
{% extends 'base.html' %}

{% block meta_tags %}      
    <title>{{post.title}} | Techcoreua</title>
    <meta name = "description" content = "{{post.preview_text|safe}}">


    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@techcoreua" />
    <meta name="twitter:creator" content="@tse_ne_ia" />
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:title" content="{{post.title}}" />
    <meta property="og:description" content="{{post.preview_text|safe}}" />
    <meta property="og:image" content="https://{{request.get_host}}{{post.main_image.url}}" />
{% endblock meta_tags %}

{% block content %}
<div class="post-header-container mt-5 pt-3">
    <div class="img-container">
        <img src="{{post.main_image.url}}" alt="" class="img-fluid header-img">
    </div>
    <div class="post-header-wrap">
        <header>
            <p class="post-header-category">Категорія: <a href="{{post.category.get_absolute_url}}">{{post.category}}</p></a>
            <h1 class="post-titleh3 p-p-dark">{{post.title}}</h1>
            <p class="post-preview">{{post.preview_text|safe}}</p>
            <img src="{{post.main_image.url}}" alt="" class="img-fluid mobile-post-img">
            <p class="autor-date-area pt-3 pb-2"><i class="far fa-user"></i> {{post.author.first_name}} {{post.author.last_name}} / <i class="far fa-clock"></i> {{post.creating_date}}</p>
        </header>
    </div>
</div>
<div class="post-page-container col-8 offset-2 mt-3">
    <div class="post-container">
        <!-- <p class="autor-date-area">{{post.author.first_name}} {{post.author.last_name}} / {{post.creating_date}}</p>
        <hr> -->
        <div class="post-text">
            <!-- <h3 class="post-titleh3 p-p-dark">{{post.title}}</h3>
            <p class="post-preview">{{post.preview_text|safe}}</p> -->
            <p class="p-p-post-text">{{post.text|safe}}</p>
            <div class="tags_cloud mt-4 bg-transparent">
                {% for tag in post_tags %}
                    <a href="{{tag.get_absolute_url}}" class="btn">{{tag.title}}</a>
                {% endfor %}
            </div>
        </div>
        <p class="text-center">Сподобався матеріал? Поділіться ним у соцмережах!</p>
        <div class="sharethis-inline-share-buttons mb-3 mt-3"></div>
        <div id="disqus_thread"></div>
        
    </div>
    <div class="sidebar">
        <div class="sidebar mb-5">

            <h3 class="category-pageh3 text-center">Останні мануали</h3><hr>
            <div class="sidebar-posts">

                {% for manual in manuals_posts %}
                <div class="sidebar-page-post">
                    <img class="img-fluid sidebar-page-post-img" src="{{manual.main_image.url}}" alt="" srcset="">
                    <div class="sidebar-page-post-text">
                        <a class="read_more" href="{{manual.get_absolute_url}}"><h4 class="post-titleh4">{{manual.title}}</h4></a>
                        <p class="autor-date-area">{{manual.author.first_name}} {{manual.author.last_name}} / {{manual.creating_date}}</p>
                    </div>
                </div>
                {% endfor %}
                
            </div>

            <h3 class="category-pageh3 text-center mt-3">Останні огляди</h3><hr>
            <div class="sidebar-posts">
                
                {% for review in review_posts %}
                <div class="sidebar-page-post">
                    <img class="img-fluid sidebar-page-post-img" src="{{review.main_image.url}}" alt="" srcset="">
                    <div class="sidebar-page-post-text">
                        <a class="read_more" href="{{review.get_absolute_url}}"><h4 class="post-titleh4">{{review.title}}</h4></a>
                        <p class="autor-date-area">{{review.author.first_name}} {{review.author.last_name}} / {{review.creating_date}}</p>
                    </div>
                </div>
                {% endfor %}

            </div>

            <h3 class="category-pageh3 text-center">Хмара тегів</h3><hr>
            <div class="tags_cloud mb-3">
                {% for tag in tags %}
                    <a href="{{tag.get_absolute_url}}" class="btn">{{tag.title}}</a>
                {% endfor %}

            </div>


        </div>

    </div>
</div>

{% endblock content %}